version: "3"

services:
  
  node:
    
    image: node:16
    
    container_name: desafio_xp
    
    tty: true
    
    stdin_open: true
    
    command: bash
    
    restart: always
    
    working_dir: /index
    
    volumes:

      - ./:/index
    
    depends_on:
      
      - db

    ports:
      
      - 3000:3000
    
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db 
      PORT: '3000'

  
  db:
    container_name: desafio_xp_db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:

      - 3306:3306


networks:

  default:

